apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-kafka-status
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 3000
  prometheus:
    enabled: false
  liveness:
    path: /internal/isalive
  readiness:
    path: /internal/isready
  startup:
    path: /internal/isready
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: dp-kafka-rest