name: Test

on:
  push:

jobs:
  gradle:
    name: gradle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: --configuration-cache test